### ISSUE TITLE
Keys reported as missing and unused

### ISSUE THREAD

**Issue by thegcat** [glebm/i18n-tasks#127]
In hacken-in/website#558 (I first linked to PR 557 of that repo, sorry for the mixup), some keys are recognised as missing and unused (see especially the fixing commit hacken-in/website@ca5d261437d1aaa24bea38c8eebe406a5accbe06), any idea what could be happening? Is there anything we can do to help debug this?

(we have obviously worked around it, but I don't think that's a good answer :-) )

**Comment by glebm** [comment]
It is indeed correct in reporting the keys as missing:
```
+--------+-----------------------------------+----------------------------+
| Locale | Key                               | Details                    |
+--------+-----------------------------------+----------------------------+
|   de   | subscriptions.delete.confirmation | You no longer participate. |
|   de   | subscriptions.push.confirmation   | You now participate.       |
|   en   | single_events.delete.confirmation | Du nimmst nicht mehr teil. |
|   en   | single_events.push.confirmation   | Du nimmst jetzt teil.      |
+--------+-----------------------------------+----------------------------+
```

en.yml does not have `single_events.{push,delete}.confirmation`:
```yaml
  single_events:
    show:
      participate: And me!
      unparticipate: Not yet.
```

de.yml does not have `subscriptions.{push,delete}.confirmation`:

```yaml
  subscriptions:
    index:
      error: Eintrag nicht gefunden.
```
These are missing because they do appear in the other locale file.

`subscriptions.{push,delete}.confirmation` do not seem to be used anywhere (at least with `git grep 'subscriptions'`).

The other unused warning is because the key is used like this:

```ruby
flash[:notice] = t "single_events.#{params[:state]}.confirmation"
```

Generally, i18n-tasks will do its best to guess the usage here, but I'd recommend to list the keys explicitly:

```ruby
# i18n-tasks-use t('single_events.push.confirmation') t('single_events.delete.confirmation')
flash[:notice] = t "single_events.#{params[:state]}.confirmation"
```
