### ISSUE TITLE
Normalization has different results in Ruby 2.2.x versus Ruby 2.3 and up.

### ISSUE THREAD

**Issue by mvz** [glebm/i18n-tasks#259]
If I run `i18n-tasks normalize` under Ruby 2.2.6, quotes are added around non-ascii strings. If I run it again under Ruby 2.4.0, those quotes are removed.

This is probably no problem usually, but since version 0.9.17 of this gem, the `health` task checks if the yaml files are normalized. This means this task fails either on Ruby 2.2.x, or on 2.3+. See [this Travis CI build](https://travis-ci.org/publify/publify/builds/265900258) for an example.

**Comment by glebm** [comment]
i18n-tasks uses psych which uses libyaml which is different by default depending on the version of Ruby.
Normally this is not a problem because an application should always run CI at the same ruby version as in the development/production environments.

For a library, you can use the [spec template](https://github.com/glebm/i18n-tasks/blob/master/templates/rspec/i18n_spec.rb) instead of running `i18n-tasks health` in CI.

Then simply skip the `'files are normalized'` test when on Ruby 2.2.6.

**Comment by mvz** [comment]
Thanks, I'll try that. It looks much cleaner than shelling out to `i18n-tasks health`, which I've been doing op to now.
