### ISSUE TITLE
Combine add-missing with tree-filter?

### ISSUE THREAD

**Issue by jawa** [glebm/i18n-tasks#287]
Hi, I've tried some variants of combining the commands but it seems that I can't get it right :-(

What I would like to do is to only add the missing translations in the specified tree filter, something like this:

`i18n-tasks tree-filter 'articles.*' | i18n-tasks add-missing`

Which would only add the missing keys in e.g. "articles" but not in "posts". Would it be possible to do?

Thanks for a great tool anyway!

**Comment by glebm** [comment]
`tree-filter` needs a tree to operate on, e.g. you can pipe it to the output of `data`. For both of these you need to specify the format (e.g. `-f yaml`), otherwise they will print in the terminal table format.

`add-missing` does not accept a tree. You can instead pipe with `tree-mv SOURCE_LANGUAGE TARGET_LANGUAGE` (e.g. `tree-mv en fr`) and then pipe with `tree-set-value`, and then `data-merge`.

**Comment by jawa** [comment]
Thanks!
I think I got what I wanted by doing something this:
`i18n-tasks missing -f yaml | i18n-tasks tree-filter 'articles.*' -f yaml | i18n-tasks tree-set-value 'TRME %{value}' -f yaml | i18n-tasks data-merge`
