### ISSUE TITLE
Unused task producing regexperror: premature end of char-class

### ISSUE THREAD

**Issue by acetinick** [glebm/i18n-tasks#354]
Hi,

I am looking to use the unused task across my very large Rails to find unused locales.  I have a lot of dynamic locales in the code,  as assume this might be causing errors.

Any way i can work out what particularly is causing the issue with the task?

I have run this task using with and without the "--no-strict" parameter.

Below is the detailed output:
![image](https://user-images.githubusercontent.com/571649/84085521-6e88ef80-a9ee-11ea-9863-84b39180ae93.png)

Ruby 2.6.6
Rails 6.0.3.1
i18n-tasks 0.9.31

**Comment by tomaadland** [comment]
I have the same problem with dynamic locales. Setting `search.strict` to `false` is not working. 

@acetinick did you find a solution for this ?

**Comment by tomaadland** [comment]
After a few hours of debugging I finally found the problem in my source. 

One of the dynamic locales is an array lookup: `t("loopup.something.in.#{somearray["element"]}")` when this is compiled to key pattern it ends up with this result `(lookup\.something\.in\.somearray[|)` which makes the conversion to Regexp fail. The open bracket `[` is the culprit here. 

Solution for my problem was to remove the array lookup into a helper method.
